#% from ".github/workflows/scsgha.yml" import actions -%#
version: 2
updates:
- package-ecosystem: "gitsubmodule"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  #% if True %#ignore:#% endif %#
  #% if True %#{{"# Actions managed by %s" % skeleton_url}}#% endif %#
#%- for action in actions %#
  #% if True %#- dependency-name: "{{action}}"#% endif %#
#%- endfor %#
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
