# Specify shared data across all 'output' destinations
# Note that the copier.yml defaults are used whenever the key is not set in this file
[defaults]
repo = "skeleton-ctt"
description = "Test snapshot of the skeleton template."
visibility = "private"
github = "bswck"
author = "bswck"
org = "bswck"
email = "bswck.dev@gmail.com"
pypi = false
docs = false
rtd = "skeleton-ctt"
tests = false
package = "skeleton_ctt"
python = "3.8"
license = "MIT"
precommit = false
ctt = true

[output.".ctt/base"]

[output.".ctt/extended"]
visibility = "public"
docs = true
tests = true
pypi = true
precommit = true
